### PR TITLE
added more table structure to layout, switched the " to ' for readability (feel free to switch back)

### PR DESCRIPTION
**Pull request by danieljmccoy**

### CODE REVIEW

**Comment by danieljmccoy** [comment]
Testing... let me know if this worked.

**Comment by danieljmccoy** [comment]
Everything shrinks down nicely.  I can adjust it more and make 100% perfect, but let's get some of the functionality down first.  Feel free to not accept/let me know necessary revisions needed.  I can shrink the tables down more or whatever need be to fit exactly how you'd like.  I'm not a bootstrap master by any means, but I'm decent at designing in %/em's so let me know

**Comment by boomer1204** [comment]
I'll look into it.  Honestly i'm not 100% sure how to even merge them
together but will look into that tonight :)

I think when I/we start focusing on the aesthetics we should remove them
from tables anyways but for now that cleans it up nicely.

Thanks!

**Comment by danieljmccoy** [comment]
Okay, cool.  We should possibly keep the city stuff as a table, since it is
tabular data, and wrap that in a flex.  That's what a 'spec' would
typically recommend.  A spec?  Wat?  We don't need no stinkin spec.  Ha.
But, yeah, whatever you have planned we can implement easily.

**Pull request merged**
